### ISSUE TITLE
Pinning fixed versions for dependencies 

### ISSUE THREAD

**Issue by m-a-r-i-u-s** [BioMemPhys-FAU/domhmm#53]
Fixed versions for the dependencies could lead to some troubles for the users as mentioned in this [conversation](https://github.com/MDAnalysis/MDAKits/pull/164#discussion_r1755932770) .

TODO
---------

Check possible ranges for the following packages:

- [x] hmmlearn
- [x] networkx
- [x] numpy
- [x] scikit-learn
- [x] script

**Comment by m-a-r-i-u-s** [comment]
With this entries the unit tests passes
    "MDAnalysis>=2.0.0",
    "hmmlearn == 0.3.2",
    "networkx >= 3.0.0",
    "numpy >= 1.26.0, <2.0.0",
    "scikit-learn >= 1.4.0",
    "scipy >= 1.13.0"

I am not entirely sure about NumPy 2.0 yet. What do you think @yusuferentunc ?

**Comment by yusuferentunc** [comment]
I think NumPy > 2.0.0 versions had some incompatibility with scikit-learn version or scipy version. Besides that, I think it looks good. 

Current problem is hmmlearn and networkx has some problem with pypi package installation. Somehow, you can install it via `pip install hmmlearn networkx` command but when encapsulating into one package `pip install domhmm` command throws error about can't find packages hmmlearn and networkx. I was working on this problem.
